cli: fix celery-run
The conversion of celery_args (a tuple) into a list is mandatory, otherwise
following error happens on celery-run:

Traceback (most recent call last):
  File ".../bin/kallithea-cli", line 11, in <module>
    load_entry_point('Kallithea', 'console_scripts', 'kallithea-cli')()
  File ".../lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File ".../lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File ".../bin/kallithea_cli_base.py", line 52, in runtime_wrapper
    return annotated(*args, **kwargs)
  File ".../bin/kallithea_cli_celery.py", line 39, in celery_run
    return cmd.run_from_argv('kallithea celery worker', celery_args)
  File ".../lib/python2.7/site-packages/celery/bin/worker.py", line 177, in run_from_argv
    *self.parse_options(prog_name, argv, command))
  File ".../lib/python2.7/site-packages/celery/bin/base.py", line 412, in parse_options
    return self.parser.parse_args(arguments)
  File "/usr/lib64/python2.7/optparse.py", line 1404, in parse_args
    args = largs + rargs
TypeError: can only concatenate list (not "tuple") to list

The problem was introduced in 1d539bb18165 in last minute changes made by Mads.